version: '2'

services:

   elasticsearch:
      image: elasticsearch:latest
      restart: always
      ports:
      - "9200:9200"
      - "9300:9300"
      volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

   kibana:
      image: kibana:latest
      restart: always
      ports:
      - "5601:5601"
      depends_on:
      - elasticsearch
      links:
      - elasticsearch:elasticsearch
      environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

   rabbitmq:
      image: rabbitmq:3-management
      restart: always
      hostname: rabbitmq
      ports:
      - "15671:15671"
      - "15672:15672"
      - "5672:5672"
      environment:
      - RABBITMQ_ERLANG_COOKIE=98098208r09wq8r908qw90er8q0w8er09q8wer908qw90er
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=yousuck
      volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

   redis:
      image: redis:3-alpine
      restart: always
      ports:
      - "6379:6379"
      volumes:
      - ./data/redis:/data
      command: ["redis-server", "--appendonly", "yes"]

   nginx:
      image: nginx:alpine
      restart: always
      volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./user_passwords.conf:/etc/nginx/user_passwords.conf:ro
      - ./admin_passwords.conf:/etc/nginx/admin_passwords.conf:ro
      links:
      - kibana:kibana
      - elasticsearch:elasticsearch
      - rabbitmq:rabbitmq
      ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
